export const documentTypes = [
  {
    document: "barangayCertificate",
    fields: [
      "fullName",
      "dateIssued",
      "address",
      "dateOfBirth",
      "nationality",
      "purpose",
    ],
    templateLocation: "/documents/barangayCertificate.pdf",
    templateLocationSign: "/documents/barangayClearance.pdf",
  },
  {
    document: "barangayClearance",
    fields: [
      "fullName",
      "dateIssued",
      "address",
      "dateOfBirth",
      "civilStatus",
      "purpose",
      "yrsOfResidency",
    ],
    templateLocation: "/documents/barangayClearance.pdf",
    templateLocationSign: "/documents/barangayClearanceSign.pdf",
  },
  {
    document: "certificateOfResidency",
    fields: [
      "fullName",
      "address",
      "yrsOfResidency",
      "purpose",
      "dateIssued",
    ],
    templateLocation: "/documents/certificateOfResidency.pdf",
    templateLocationSign: "/documents/barangayClearance.pdf",
  },
  {
    document: "certificateOfIndigency",
    fields: [
      "fullName",
      "address",
      "purpose",
      "dateIssued",
    ],
    templateLocation: "/documents/certificateOfIndigency.pdf",
    templateLocationSign: "/documents/barangayClearance.pdf",
  },
  {
    document: "certificateOfGoodMoralCharacter",
    fields: [
      "fullName",
      "address",
      "purpose",
      "dateIssued",
    ],
    templateLocation: "/documents/certificateOfGoodMoralCharacter.pdf",
    templateLocationSign: "/documents/barangayClearance.pdf",
  },
  {
    document: "certificateOfUnemployment",
    fields: [
      "fullName",
      "address",
      "dateOfBirth",
      "purpose",
      "dateIssued",
    ],
    templateLocation: "/documents/certificateOfUnemployment.pdf",
    templateLocationSign: "/documents/barangayClearance.pdf",
  },
  {
    document: "barangayBusinessClearance",
    fields: [
      "fullName",
      "businessName",
      "businessAddress",
      "businessType",
      "businessNature",
      "address",
      "dateIssued",
    ],
    templateLocation: "/documents/barangayBusinessClearance.pdf",
    templateLocationSign: "/documents/barangayClearance.pdf",
  },
];